class_name Geo
extends RefCounted
## Map of Poland: the 25 biggest cities plus Zakopane, Zamość and Łomża, the main roads between them, the towns
## passed on the way and the regions crossed. Distances are approximate road kilometres.
## `road` is the road number, or [[km from `a` where it ends, number], ...] when the leg changes road
## (A = motorway, S = expressway, DK = national road, DW = regional road; as of 2026).
## Towns are [name, km from `a`], zones [km from `a` where the zone ends, biome, region]. Travelling b -> a mirrors them.

## lat/lon in degrees, pop in thousands (approx.)
const CITIES := {
	"warszawa": {"name": "Warszawa", "lat": 52.23, "lon": 21.01, "pop": 1860, "voiv": "mazowieckie"},
	"krakow": {"name": "Kraków", "lat": 50.06, "lon": 19.94, "pop": 800, "voiv": "małopolskie"},
	"wroclaw": {"name": "Wrocław", "lat": 51.11, "lon": 17.03, "pop": 670, "voiv": "dolnośląskie"},
	"lodz": {"name": "Łódź", "lat": 51.76, "lon": 19.46, "pop": 650, "voiv": "łódzkie"},
	"poznan": {"name": "Poznań", "lat": 52.41, "lon": 16.93, "pop": 540, "voiv": "wielkopolskie"},
	"gdansk": {"name": "Gdańsk", "lat": 54.35, "lon": 18.65, "pop": 490, "voiv": "pomorskie"},
	"szczecin": {"name": "Szczecin", "lat": 53.43, "lon": 14.55, "pop": 390, "voiv": "zachodniopomorskie"},
	"lublin": {"name": "Lublin", "lat": 51.25, "lon": 22.57, "pop": 330, "voiv": "lubelskie"},
	"bydgoszcz": {"name": "Bydgoszcz", "lat": 53.12, "lon": 18.01, "pop": 330, "voiv": "kujawsko-pomorskie"},
	"bialystok": {"name": "Białystok", "lat": 53.13, "lon": 23.16, "pop": 290, "voiv": "podlaskie"},
	"katowice": {"name": "Katowice", "lat": 50.26, "lon": 19.02, "pop": 280, "voiv": "śląskie"},
	"gdynia": {"name": "Gdynia", "lat": 54.52, "lon": 18.53, "pop": 240, "voiv": "pomorskie"},
	"czestochowa": {"name": "Częstochowa", "lat": 50.81, "lon": 19.12, "pop": 210, "voiv": "śląskie"},
	"radom": {"name": "Radom", "lat": 51.40, "lon": 21.15, "pop": 200, "voiv": "mazowieckie"},
	"rzeszow": {"name": "Rzeszów", "lat": 50.04, "lon": 22.00, "pop": 200, "voiv": "podkarpackie"},
	"torun": {"name": "Toruń", "lat": 53.01, "lon": 18.60, "pop": 195, "voiv": "kujawsko-pomorskie"},
	"kielce": {"name": "Kielce", "lat": 50.87, "lon": 20.63, "pop": 185, "voiv": "świętokrzyskie"},
	"olsztyn": {"name": "Olsztyn", "lat": 53.78, "lon": 20.48, "pop": 170, "voiv": "warmińsko-mazurskie"},
	"bielsko": {"name": "Bielsko-Biała", "lat": 49.82, "lon": 19.04, "pop": 165, "voiv": "śląskie"},
	"zielona_gora": {"name": "Zielona Góra", "lat": 51.94, "lon": 15.51, "pop": 135, "voiv": "lubuskie"},
	"opole": {"name": "Opole", "lat": 50.67, "lon": 17.93, "pop": 125, "voiv": "opolskie"},
	"gorzow": {"name": "Gorzów Wielkopolski", "lat": 52.73, "lon": 15.24, "pop": 115, "voiv": "lubuskie"},
	"plock": {"name": "Płock", "lat": 52.55, "lon": 19.70, "pop": 115, "voiv": "mazowieckie"},
	"elblag": {"name": "Elbląg", "lat": 54.16, "lon": 19.40, "pop": 115, "voiv": "warmińsko-mazurskie"},
	"koszalin": {"name": "Koszalin", "lat": 54.19, "lon": 16.17, "pop": 105, "voiv": "zachodniopomorskie"},
	"lomza": {"name": "Łomża", "lat": 53.18, "lon": 22.06, "pop": 62, "voiv": "podlaskie"},
	"zamosc": {"name": "Zamość", "lat": 50.72, "lon": 23.25, "pop": 60, "voiv": "lubelskie"},
	"zakopane": {"name": "Zakopane", "lat": 49.30, "lon": 19.95, "pop": 26, "voiv": "małopolskie"},
}

const ROADS := [
	{"a": "krakow", "b": "katowice", "road": "A4", "km": 80,
		"towns": [["Chrzanów", 40], ["Jaworzno", 55], ["Mysłowice", 70]],
		"zones": [[30, "jura", "Wyżyna Krakowsko-Częstochowska"], [80, "industrial", "Górnośląski Okręg Przemysłowy"]]},
	{"a": "krakow", "b": "rzeszow", "road": "A4", "km": 165,
		"towns": [["Bochnia", 40], ["Brzesko", 55], ["Tarnów", 80], ["Dębica", 120], ["Ropczyce", 135], ["Sędziszów Małopolski", 145]],
		"zones": [[55, "foothills", "Pogórze Karpackie"], [125, "fields", "Kotlina Sandomierska"], [165, "foothills", "Pogórze Rzeszowskie"]]},
	{"a": "krakow", "b": "kielce", "road": "S7", "km": 115,
		"towns": [["Miechów", 40], ["Jędrzejów", 75], ["Chęciny", 100]],
		"zones": [[60, "upland", "Wyżyna Miechowska"], [95, "fields", "Niecka Nidziańska"], [115, "forest", "Góry Świętokrzyskie"]]},
	{"a": "krakow", "b": "bielsko", "road": "DK52", "km": 90,
		"towns": [["Kalwaria Zebrzydowska", 35], ["Wadowice", 50], ["Andrychów", 62], ["Kęty", 72]],
		"zones": [[30, "foothills", "Pogórze Wielickie"], [90, "mountains", "Beskid Mały"]]},
	{"a": "katowice", "b": "bielsko", "road": "S1", "km": 60,
		"towns": [["Tychy", 18], ["Pszczyna", 35], ["Czechowice-Dziedzice", 48]],
		"zones": [[25, "industrial", "Górnośląski Okręg Przemysłowy"], [45, "forest", "Kotlina Oświęcimska"], [60, "mountains", "Beskid Śląski"]]},
	{"a": "katowice", "b": "czestochowa", "road": "A1", "km": 75,
		"towns": [["Piekary Śląskie", 15], ["Siewierz", 38], ["Koziegłowy", 52]],
		"zones": [[25, "industrial", "Górnośląski Okręg Przemysłowy"], [75, "jura", "Wyżyna Krakowsko-Częstochowska"]]},
	{"a": "katowice", "b": "opole", "road": "A4", "km": 100,
		"towns": [["Gliwice", 25], ["Strzelce Opolskie", 65]],
		"zones": [[30, "industrial", "Górnośląski Okręg Przemysłowy"], [55, "fields", "Wyżyna Śląska"], [75, "upland", "Chełm (Góra Świętej Anny)"], [100, "fields", "Nizina Śląska"]]},
	{"a": "opole", "b": "wroclaw", "road": "A4", "km": 95,
		"towns": [["Brzeg", 45], ["Oława", 70]],
		"zones": [[30, "fields", "Nizina Śląska"], [50, "forest", "Bory Niemodlińskie"], [95, "fields", "Nizina Śląska"]]},
	{"a": "czestochowa", "b": "lodz", "road": "A1", "km": 125,
		"towns": [["Radomsko", 45], ["Kamieńsk", 60], ["Piotrków Trybunalski", 80], ["Tuszyn", 105]],
		"zones": [[50, "fields", "Wyżyna Wieluńska"], [80, "forest", "Równina Piotrkowska"], [125, "fields", "Wzniesienia Łódzkie"]]},
	{"a": "czestochowa", "b": "opole", "road": "DK46", "km": 95,
		"towns": [["Lubliniec", 35], ["Dobrodzień", 55], ["Ozimek", 75]],
		"zones": [[45, "forest", "Lasy Lublinieckie"], [95, "fields", "Równina Opolska"]]},
	{"a": "lodz", "b": "warszawa", "road": "A2", "km": 135,
		"towns": [["Stryków", 20], ["Łowicz", 60], ["Żyrardów", 90], ["Grodzisk Mazowiecki", 105], ["Pruszków", 120]],
		"zones": [[25, "fields", "Wzniesienia Łódzkie"], [135, "fields", "Mazowsze"]]},
	{"a": "lodz", "b": "poznan", "road": "A2", "km": 210,
		"towns": [["Łęczyca", 40], ["Dąbie", 75], ["Koło", 90], ["Konin", 115], ["Słupca", 140], ["Września", 165]],
		"zones": [[45, "fields", "Równina Łęczycka"], [100, "fields", "Dolina Warty"], [125, "industrial", "Zagłębie Konińskie"], [210, "fields", "Wielkopolska"]]},
	{"a": "lodz", "b": "torun", "road": "A1", "km": 180,
		"towns": [["Stryków", 20], ["Piątek", 45], ["Kutno", 65], ["Kowal", 110], ["Włocławek", 125]],
		"zones": [[50, "fields", "Ziemia Łęczycka"], [110, "fields", "Równina Kutnowska"], [180, "fields", "Kujawy"]]},
	{"a": "lodz", "b": "wroclaw", "road": "S8", "km": 210,
		"towns": [["Łask", 30], ["Sieradz", 55], ["Wieruszów", 110], ["Kępno", 125], ["Syców", 150], ["Oleśnica", 180]],
		"zones": [[110, "fields", "Ziemia Sieradzka"], [165, "forest", "Wzgórza Ostrzeszowskie"], [210, "fields", "Nizina Śląska"]]},
	{"a": "wroclaw", "b": "poznan", "road": "S5", "km": 180,
		"towns": [["Trzebnica", 25], ["Rawicz", 85], ["Leszno", 105], ["Kościan", 135], ["Stęszew", 160]],
		"zones": [[30, "upland", "Wzgórza Trzebnickie"], [70, "lakes", "Dolina Baryczy"], [100, "fields", "Wielkopolska"], [125, "lakes", "Pojezierze Leszczyńskie"], [180, "fields", "Wielkopolska"]]},
	{"a": "wroclaw", "b": "zielona_gora", "road": [[65, "A4"], [190, "S3"]], "km": 190,
		"towns": [["Środa Śląska", 35], ["Legnica", 65], ["Lubin", 90], ["Polkowice", 105], ["Nowa Sól", 165]],
		"zones": [[50, "fields", "Nizina Śląska"], [115, "industrial", "Legnicko-Głogowski Okręg Miedziowy"], [190, "forest", "Dolina Odry"]]},
	{"a": "poznan", "b": "bydgoszcz", "road": "S5", "km": 130,
		"towns": [["Gniezno", 50], ["Żnin", 90], ["Szubin", 105]],
		"zones": [[65, "lakes", "Pojezierze Gnieźnieńskie"], [130, "fields", "Pałuki"]]},
	{"a": "poznan", "b": "zielona_gora", "road": [[95, "A2"], [135, "S3"]], "km": 135,
		"towns": [["Buk", 30], ["Nowy Tomyśl", 60], ["Świebodzin", 95], ["Sulechów", 115]],
		"zones": [[65, "fields", "Wielkopolska"], [135, "lakes", "Pojezierze Lubuskie"]]},
	{"a": "poznan", "b": "koszalin", "road": [[170, "DK11"], [240, "S11"]], "km": 240,
		"towns": [["Oborniki", 35], ["Chodzież", 70], ["Piła", 100], ["Jastrowie", 125], ["Szczecinek", 170], ["Bobolice", 200]],
		"zones": [[65, "fields", "Wielkopolska"], [120, "forest", "Dolina Noteci"], [190, "lakes", "Pojezierze Szczecineckie"], [240, "forest", "Pomorze Środkowe"]]},
	{"a": "bydgoszcz", "b": "torun", "road": "S10", "km": 50,
		"towns": [["Solec Kujawski", 20]],
		"zones": [[50, "forest", "Puszcza Bydgoska"]]},
	{"a": "torun", "b": "gdansk", "road": "A1", "km": 175,
		"towns": [["Grudziądz", 60], ["Pelplin", 115], ["Tczew", 140], ["Pruszcz Gdański", 165]],
		"zones": [[60, "fields", "Ziemia Chełmińska"], [100, "forest", "Bory Tucholskie"], [175, "fields", "Kociewie"]]},
	{"a": "torun", "b": "plock", "road": [[55, "DK91"], [110, "DK62"]], "km": 110,
		"towns": [["Ciechocinek", 20], ["Włocławek", 55], ["Dobrzyków", 85]],
		"zones": [[60, "fields", "Kujawy"], [110, "fields", "Dolina Wisły"]]},
	{"a": "gdansk", "b": "gdynia", "road": "", "km": 25,
		"towns": [["Sopot", 12]],
		"zones": [[25, "coast", "Trójmiasto"]]},
	{"a": "gdansk", "b": "elblag", "road": "S7", "km": 60,
		"towns": [["Nowy Dwór Gdański", 35]],
		"zones": [[60, "zulawy", "Żuławy Wiślane"]]},
	{"a": "gdynia", "b": "koszalin", "road": "S6", "km": 170,
		"towns": [["Wejherowo", 20], ["Lębork", 60], ["Słupsk", 115], ["Sławno", 140]],
		"zones": [[30, "forest", "Puszcza Darżlubska"], [70, "lakes", "Kaszuby"], [170, "coast", "Pobrzeże Koszalińskie"]]},
	{"a": "koszalin", "b": "szczecin", "road": "S6", "km": 165,
		"towns": [["Karlino", 30], ["Płoty", 70], ["Nowogard", 100], ["Goleniów", 125]],
		"zones": [[40, "coast", "Pobrzeże Koszalińskie"], [110, "fields", "Równina Nowogardzka"], [150, "forest", "Puszcza Goleniowska"], [165, "fields", "Dolina Dolnej Odry"]]},
	{"a": "szczecin", "b": "gorzow", "road": "S3", "km": 105,
		"towns": [["Pyrzyce", 45], ["Myślibórz", 75]],
		"zones": [[50, "fields", "Równina Pyrzycka"], [105, "lakes", "Pojezierze Myśliborskie"]]},
	{"a": "szczecin", "b": "bydgoszcz", "road": [[35, "S10"], [260, "DK10"]], "km": 260,
		"towns": [["Stargard", 35], ["Kalisz Pomorski", 85], ["Wałcz", 130], ["Piła", 165], ["Nakło nad Notecią", 230]],
		"zones": [[50, "fields", "Równina Pyrzycka"], [150, "lakes", "Pojezierze Wałeckie"], [190, "forest", "Dolina Noteci"], [260, "fields", "Krajna"]]},
	{"a": "gorzow", "b": "zielona_gora", "road": "S3", "km": 110,
		"towns": [["Skwierzyna", 25], ["Międzyrzecz", 45], ["Świebodzin", 70], ["Sulechów", 95]],
		"zones": [[30, "forest", "Kotlina Gorzowska"], [75, "lakes", "Pojezierze Łagowskie"], [110, "forest", "Ziemia Lubuska"]]},
	{"a": "elblag", "b": "olsztyn", "road": [[70, "S7"], [105, "DK16"]], "km": 105,
		"towns": [["Pasłęk", 20], ["Miłomłyn", 55], ["Ostróda", 70]],
		"zones": [[25, "fields", "Wysoczyzna Elbląska"], [75, "lakes", "Pojezierze Iławskie"], [105, "forest", "Warmia"]]},
	{"a": "olsztyn", "b": "warszawa", "road": [[30, "S51"], [210, "S7"]], "km": 210,
		"towns": [["Olsztynek", 30], ["Nidzica", 55], ["Mława", 100], ["Płońsk", 140], ["Łomianki", 195]],
		"zones": [[55, "lakes", "Warmia i Mazury"], [100, "fields", "Wzniesienia Mławskie"], [210, "fields", "Mazowsze"]]},
	{"a": "olsztyn", "b": "bialystok", "road": [[150, "DK16"], [230, "DK65"]], "km": 230,
		"towns": [["Biskupiec", 30], ["Mrągowo", 60], ["Orzysz", 95], ["Ełk", 125], ["Grajewo", 150], ["Mońki", 190]],
		"zones": [[130, "lakes", "Mazury"], [175, "lakes", "Dolina Biebrzy"], [230, "podlasie", "Podlasie"]]},
	{"a": "warszawa", "b": "bialystok", "road": "S8", "km": 200,
		"towns": [["Radzymin", 25], ["Wyszków", 55], ["Ostrów Mazowiecka", 95], ["Zambrów", 130]],
		"zones": [[40, "fields", "Mazowsze"], [80, "forest", "Puszcza Biała"], [140, "fields", "Wysoczyzna Wysokomazowiecka"], [200, "podlasie", "Podlasie"]]},
	{"a": "warszawa", "b": "lublin", "road": "S17", "km": 170,
		"towns": [["Garwolin", 60], ["Ryki", 90], ["Kurów", 125]],
		"zones": [[105, "fields", "Mazowsze"], [170, "upland", "Wyżyna Lubelska"]]},
	{"a": "warszawa", "b": "radom", "road": "S7", "km": 100,
		"towns": [["Grójec", 40], ["Białobrzegi", 65]],
		"zones": [[25, "fields", "Mazowsze"], [70, "orchard", "Sady Grójeckie"], [100, "fields", "Równina Radomska"]]},
	{"a": "warszawa", "b": "plock", "road": [[40, "S7"], [115, "DK62"]], "km": 115,
		"towns": [["Łomianki", 15], ["Zakroczym", 40], ["Wyszogród", 70]],
		"zones": [[35, "forest", "Puszcza Kampinoska"], [115, "fields", "Dolina Wisły"]]},
	{"a": "radom", "b": "kielce", "road": "S7", "km": 80,
		"towns": [["Szydłowiec", 30], ["Skarżysko-Kamienna", 45], ["Suchedniów", 55]],
		"zones": [[25, "fields", "Równina Radomska"], [80, "forest", "Góry Świętokrzyskie"]]},
	{"a": "lublin", "b": "rzeszow", "road": "S19", "km": 170,
		"towns": [["Kraśnik", 50], ["Janów Lubelski", 80], ["Nisko", 110], ["Sokołów Małopolski", 145]],
		"zones": [[50, "upland", "Wyżyna Lubelska"], [120, "forest", "Lasy Janowskie"], [170, "fields", "Kotlina Sandomierska"]]},
	{"a": "lublin", "b": "bialystok", "road": [[25, "S19"], [205, "DK19"], [250, "S19"]], "km": 250,
		"towns": [["Lubartów", 25], ["Radzyń Podlaski", 65], ["Międzyrzec Podlaski", 95], ["Siemiatycze", 165], ["Bielsk Podlaski", 205]],
		"zones": [[35, "upland", "Wyżyna Lubelska"], [100, "fields", "Południowe Podlasie"], [250, "podlasie", "Podlasie"]]},
	{"a": "lublin", "b": "kielce", "road": [[50, "S19"], [170, "DK74"]], "km": 170,
		"towns": [["Kraśnik", 50], ["Annopol", 75], ["Opatów", 115], ["Łagów", 135]],
		"zones": [[60, "upland", "Wyżyna Lubelska"], [100, "fields", "Dolina Wisły"], [135, "upland", "Wyżyna Sandomierska"], [170, "forest", "Góry Świętokrzyskie"]]},
	{"a": "krakow", "b": "zakopane", "road": [[65, "S7"], [105, "DK47"]], "km": 105,
		"towns": [["Myślenice", 35], ["Lubień", 55], ["Rabka-Zdrój", 65], ["Nowy Targ", 85]],
		"zones": [[25, "foothills", "Pogórze Wielickie"], [70, "mountains", "Beskidy"], [105, "mountains", "Podhale"]]},
	{"a": "lublin", "b": "zamosc", "road": "S17", "km": 90,
		"towns": [["Piaski", 25], ["Krasnystaw", 55]],
		"zones": [[60, "upland", "Wyżyna Lubelska"], [90, "fields", "Padół Zamojski"]]},
	{"a": "zamosc", "b": "rzeszow", "road": [[20, "DK74"], [110, ""], [135, "DW877"], [160, "A4"]], "km": 160,
		"towns": [["Szczebrzeszyn", 20], ["Biłgoraj", 50], ["Leżajsk", 110], ["Łańcut", 135]],
		"zones": [[30, "upland", "Roztocze"], [90, "forest", "Puszcza Solska"], [130, "fields", "Kotlina Sandomierska"], [160, "foothills", "Pogórze Rzeszowskie"]]},
	{"a": "warszawa", "b": "lomza", "road": [[95, "S8"], [150, "S61"]], "km": 150,
		"towns": [["Radzymin", 25], ["Wyszków", 55], ["Ostrów Mazowiecka", 95], ["Śniadowo", 120]],
		"zones": [[40, "fields", "Mazowsze"], [80, "forest", "Puszcza Biała"], [150, "fields", "Ziemia Łomżyńska"]]},
	{"a": "lomza", "b": "bialystok", "road": [[50, "DK64"], [80, "S8"]], "km": 80,
		"towns": [["Wizna", 25], ["Tykocin", 55]],
		"zones": [[35, "lakes", "Dolina Narwi"], [80, "podlasie", "Podlasie"]]},
	{"a": "lomza", "b": "olsztyn", "road": [[75, "DK63"], [135, "DK58"], [180, "DK53"]], "km": 180,
		"towns": [["Kolno", 30], ["Pisz", 75], ["Ruciane-Nida", 95], ["Szczytno", 135]],
		"zones": [[40, "fields", "Kurpie"], [100, "forest", "Puszcza Piska"], [150, "lakes", "Mazury"], [180, "forest", "Warmia"]]},
]

## Short facts shown when the player drives through (big cities and selected towns).
const FACTS := {
	"Warszawa": "Stolica Polski, położona nad Wisłą",
	"Kraków": "Dawna stolica Polski, zamek królewski na Wawelu",
	"Wrocław": "Miasto na wyspach Odry, z ponad stu mostami",
	"Łódź": "Dawne centrum przemysłu włókienniczego, ulica Piotrkowska",
	"Poznań": "Koziołki na ratuszu, Ostrów Tumski - kolebka państwa polskiego",
	"Gdańsk": "Fontanna Neptuna i Żuraw nad Motławą, tu narodziła się Solidarność",
	"Szczecin": "Wielki port nad Odrą, Wały Chrobrego",
	"Lublin": "W 1569 r. zawarto tu Unię Lubelską",
	"Bydgoszcz": "Miasto nad Brdą i Kanałem Bydgoskim",
	"Białystok": "Pałac Branickich nazywany Wersalem Podlasia",
	"Katowice": "Stolica Górnego Śląska, hala Spodek",
	"Gdynia": "Port zbudowany w dwudziestoleciu międzywojennym, statek Dar Pomorza",
	"Częstochowa": "Sanktuarium na Jasnej Górze",
	"Radom": "Słynie z pokazów lotniczych Air Show",
	"Rzeszów": "Stolica Podkarpacia, podziemna trasa turystyczna pod rynkiem",
	"Toruń": "Miasto Mikołaja Kopernika i pierników",
	"Kielce": "Stolica regionu świętokrzyskiego, rezerwat Kadzielnia",
	"Olsztyn": "Stolica Warmii, na zamku mieszkał Mikołaj Kopernik",
	"Bielsko-Biała": "Tu powstały bajki o Bolku i Lolku",
	"Zielona Góra": "Miasto wina, co roku święto Winobrania",
	"Opole": "Stolica polskiej piosenki - Krajowy Festiwal Piosenki Polskiej",
	"Gorzów Wielkopolski": "Miasto nad Wartą, słynie z żużla",
	"Płock": "W latach 1079-1138 stolica Polski",
	"Elbląg": "Kanał Elbląski - statki pokonują tu wzgórza na pochylniach",
	"Koszalin": "Kilkanaście kilometrów od Bałtyku, Góra Chełmska",
	"Zakopane": "Zimowa stolica Polski, u stóp Tatr",
	"Zamość": "Renesansowe miasto idealne, Stare Miasto na liście UNESCO",
	"Łomża": "Miasto nad Narwią, na skraju Kurpiów",
	"Nowy Targ": "Stolica Podhala",
	"Rabka-Zdrój": "Uzdrowisko nazywane miastem dzieci świata",
	"Szczebrzeszyn": "W Szczebrzeszynie chrząszcz brzmi w trzcinie",
	"Łańcut": "Zamek z kolekcją dawnych powozów",
	"Leżajsk": "Bazylika słynąca z zabytkowych organów",
	"Tykocin": "Barokowe miasteczko nad Narwią z wielką synagogą",
	"Wizna": "Bitwa pod Wizną w 1939 r. - polskie Termopile",
	"Ruciane-Nida": "Wśród jezior i lasów Puszczy Piskiej",
	"Bochnia": "Najstarsza kopalnia soli w Polsce",
	"Tarnów": "Uchodzi za najcieplejsze miasto w Polsce",
	"Wadowice": "Miasto rodzinne papieża Jana Pawła II",
	"Kalwaria Zebrzydowska": "Sanktuarium wpisane na listę UNESCO",
	"Pszczyna": "Zamek i pokazowa zagroda żubrów",
	"Tychy": "Znane z browaru i fabryki samochodów",
	"Gliwice": "Radiostacja - najwyższa drewniana wieża w Europie",
	"Strzelce Opolskie": "W pobliżu Góra Świętej Anny",
	"Brzeg": "Zamek Piastów Śląskich",
	"Trzebnica": "Sanktuarium świętej Jadwigi Śląskiej",
	"Legnica": "W 1241 r. stoczono tu bitwę z Mongołami",
	"Lubin": "Kopalnie miedzi - Zagłębie Miedziowe",
	"Polkowice": "Kopalnie miedzi - Zagłębie Miedziowe",
	"Konin": "Kopalnie węgla brunatnego i elektrownie",
	"Września": "Strajk dzieci wrzesińskich w obronie języka polskiego (1901)",
	"Łowicz": "Kolorowe wycinanki i stroje ludowe",
	"Żyrardów": "Dawna osada fabryczna przemysłu lnianego",
	"Piątek": "Uznawany za geometryczny środek Polski",
	"Kutno": "Miasto róż",
	"Włocławek": "Zapora na Wiśle i Jezioro Włocławskie",
	"Ciechocinek": "Uzdrowisko z tężniami solankowymi",
	"Piotrków Trybunalski": "Dawna siedziba Trybunału Koronnego",
	"Gniezno": "Pierwsza stolica Polski, Drzwi Gnieźnieńskie",
	"Żnin": "Niedaleko Biskupin - osada sprzed ok. 2700 lat",
	"Grudziądz": "Spichrze nad Wisłą",
	"Pelplin": "W katedrze przechowywana jest Biblia Gutenberga",
	"Sopot": "Najdłuższe drewniane molo w Europie",
	"Nowy Dwór Gdański": "Stolica Żuław",
	"Olsztynek": "Niedaleko pole bitwy pod Grunwaldem (1410)",
	"Piła": "Miasto urodzenia Stanisława Staszica",
	"Świebodzin": "Pomnik Chrystusa Króla",
	"Międzyrzecz": "Bunkry Międzyrzeckiego Rejonu Umocnionego",
	"Grójec": "Zagłębie sadownicze - stąd pochodzi wiele polskich jabłek",
	"Jędrzejów": "Muzeum zegarów im. Przypkowskich",
	"Chęciny": "Ruiny zamku królewskiego na wzgórzu",
}

## Poland's outline as [lon, lat], clockwise from Świnoujście (simplified).
const BORDER := [
	[14.22, 53.93], [14.45, 53.94], [14.80, 54.04], [15.20, 54.13], [15.58, 54.18], [16.20, 54.31], [16.40, 54.44],
	[16.85, 54.59], [17.30, 54.73], [17.55, 54.77], [18.00, 54.82], [18.33, 54.84], [18.42, 54.79], [18.41, 54.72],
	[18.56, 54.52], [18.57, 54.44], [18.70, 54.40], [19.00, 54.35], [19.40, 54.38], [19.63, 54.45], [20.30, 54.42],
	[21.30, 54.33], [22.00, 54.35], [22.79, 54.36], [23.05, 54.27], [23.35, 54.15], [23.50, 53.95], [23.60, 53.75],
	[23.65, 53.50], [23.92, 53.15], [23.94, 52.70], [23.40, 52.50], [23.20, 52.30], [23.62, 52.07], [23.60, 51.75],
	[23.55, 51.54], [23.65, 51.30], [23.80, 51.17], [24.10, 50.85], [24.10, 50.55], [23.70, 50.38], [23.25, 50.08],
	[22.95, 49.80], [22.65, 49.55], [22.75, 49.25], [22.89, 49.08], [22.50, 49.10], [22.10, 49.20], [21.70, 49.40],
	[21.00, 49.42], [20.60, 49.38], [20.35, 49.40], [20.10, 49.20], [19.85, 49.20], [19.80, 49.38], [19.53, 49.57],
	[19.20, 49.50], [18.85, 49.52], [18.63, 49.75], [18.57, 49.92], [18.30, 49.95], [18.05, 50.05], [17.75, 50.10],
	[17.60, 50.27], [17.38, 50.31], [17.00, 50.45], [16.90, 50.40], [16.80, 50.20], [16.67, 50.15], [16.40, 50.30],
	[16.20, 50.45], [16.40, 50.60], [16.25, 50.66], [15.90, 50.68], [15.40, 50.80], [15.00, 50.88], [14.82, 50.87],
	[15.00, 51.15], [14.95, 51.45], [14.74, 51.53], [14.73, 51.95], [14.60, 52.10], [14.56, 52.35], [14.63, 52.59],
	[14.20, 52.85], [14.40, 53.25], [14.40, 53.45], [14.27, 53.70],
]
const HEL := [[18.42, 54.79], [18.62, 54.70], [18.80, 54.60]]

static func city(id: String) -> Dictionary:
	return CITIES[id]

static func city_ids() -> Array:
	return CITIES.keys()

static func fact(name: String) -> String:
	return FACTS.get(name, "")
